### PR TITLE
Added a setup script to install dependencies

### PR DESCRIPTION
**Pull request by MrSupiri**
Issue: #28

### CODE REVIEW

**Comment by paynejacob** [comment]
Instead of `go-get-tool`  you can use `go install <pkg>`.  Also we should just put all the calls under setup instead of breaking kustomize and controllergen into their own commands.  The names are not descriptive and it makes it hard to understand what setup is doing.

**Review by paynejacob — CHANGES_REQUESTED** [review]
Instead of` go-get-tool` you can use `go install <pkg>`. Also we should just put all the calls under setup instead of breaking kustomize and controllergen into their own commands. The names are not descriptive and it makes it hard to understand what setup is doing.

**Comment by MrSupiri** [comment]
This is something kubebuilder created, I think the reason is to keep the right version locally without conflicting with other things installed in the system. with the command in the current make file, it's gonna download the binaries to `bin` folder under the repo which is in gitignore.

I can change it if you want

**Comment by MrSupiri** [comment]
> Also we should just put all the calls under setup instead of breaking kustomize and controllergen into their own command

I merged them to `make setup` rule. but personally, I think it's better to have a separate course for example `make manifests` only need controller-gen. with this setup, it will make sure even frontend dependencies are installed to before generating CRDs

**Review by paynejacob — APPROVED** [review]

**Pull request merged**
